'use strict';

resource.append('es', {
    // Buildings
    airport:          "Aeropuerto",
    amusement_park:   "Parque de atracciones",
    bank:             "Banco",
    bulldoze:         "Excavadora",
    casino:           "Casino",
    castle:           null,
    coal_power_plant: "Carbón termoeléctrica",
    crossing:         null,
    c_zone:           "Zona comercial",
    fire_dept:        "Cuerpo de Bomberos",
    fire_hq:          null,
    garden:           "Jardín",
    gas_power_plant:  "Gas termoeléctrica",
    goods_st:         "Estación de mercancías",
    hospital:         "Hospital",
    i_zone:           "Zona industrial",
    land:             "Tierra",
    land_clear:       "Campo Abierto",
    land_fill:        "Relleno de Tierra",
    nuke_power_plant: "Central nuclear",
    police_dept:      "Departamento de Policia",
    police_hq:        null,
    railroad:         "Ferrocarril",
    rail_bridge:      "Puente del Ferrocarril",
    road:             "Carretera",
    road_bridge:      "Puente del Carretera",
    rubble:           "Escombros",
    r_zone:           "Zona residencial",
    school:           "Colecio",
    sea_port:         "Puerto",
    stadium:          "Estadio",
    station:          "Estación",
    terminal_station: "Estación de Termini",
    tower:            "Torre",
    tree:             "Árbol",
    water_area:       "Agua",
    wire:             "Línea eléctrica",
    your_house:       "Tu casa",
    zoo:              null,

    // UI
    all_zones:        "Zonas RCIs",
    arrested:         "Detenido",
    assessed_value:   "Tasación $",
    audiences:        "Audiencias",
    auto_bulldoze:    "Excavadora auto",
    bankrupt:         "Arruinado",
    bond:             "Pago de bonos",
    budget:           "Presupuesto",
    budget_draft:     "Borrador del Presupuesto",
    c_zones:          "Zonas Cs",
    cancel:           "Cancelar",
    city_scale:       "Categoría",
    coast:            "Costa",
    color_bf_mode:    null,
    commitment:       "Compromiso publico",
    cost:             "Costo",
    crime:            "Crimen",
    current_funds:    "Fondos actuales",
    debt:             "Pago de la deuda",
    developed:        "Desarrollado",
    difficulty:       "Dificultad",
    disaster:         "Desastre",
    dispatched:       "Enviado",
    download:         "Descargar",
    election:         "Elección",
    election_result:  "Resultado de las elecciones",
    estimeted_funds:  "Fondos estimados",
    evaluation:       "Evaluación",
    expenses:         "Gastos",
    file:             "Archivo",
    fire_cov:         "Cobertura Bomberos",
    fire_depts:       "Bomberos",
    fire_funds:       "Fondos de Bomberos",
    freight_volume:   "Volumen de carga",
    funds:            "Fondos",
    gdp:              "PIB $",
    generate_terrain: "Generar terreno",
    get_random:       "Nombre aleatorio",
    goto_menu:        "Reinicia el juego",
    graph:            "Gráfico",
    growth_last_year: "Aumento(Año)",
    help:             "Ayuda",
    hidden_assets:    "Activos ocultos",
    hospitals:        "Hospitales",
    housing_cost:     "Gastos de vivienda",
    i_zones:          "Zonas Is",
    island:           "Isla",
    import_csv:       "Importar desde CSV",
    import_mp:        "Importar desde Micropolis",
    incomes:          "Ingresos",
    inspect:          "Inspeccionar",
    lake:             "Lago",
    land_value:       "Precio del Terreno",
    load_file:        "Carga del Archivo",
    map:              "Mapa",
    max_output:       "Salida máxima",
    naming_city:      "Nombrando tu ciudad",
    next_funds:       "Fondos del próximo año",
    not_available:    "No disponible",
    ok:               "Acuerdo",
    options:          "Opciones",
    passengers:       "Pasajeros",
    patients:         "Pacientes",
    police_cov:       "Cobertura Policial",
    police_depts:     "Policia",
    police_funds:     "Fondos de Policia",
    pollution:        "Polución",
    population:       "Población",
    pop_density:      "Densidad de población",
    pop_growth:       "Crecimiento de la población",
    popup_window:     "Ventana emergente",
    power_grid:       "Red eléctrica",
    power_outage:     "Apagón",
    power_plants:     "Plantas de energía",
    power_supplied:   "Suministrado",
    power_req:        "Potencia requerida",
    public_opinion:   "Opinión Pública",
    quit:             "Dejar",
    r_zones:          "Zonas Rs",
    radioactivity:    "Radioactividad",
    river:            "Río",
    ruleset:          "Reglas",
    save_file:        "Salvar a archivo",
    scenario:         "Guión",
    schools:          "Escuelas",
    score:            "Puntuación",
    sound_effect:     "Efecto de sonido",
    special_income:   "Ingresos especiales",
    start_city:       "Empezar nueva ciudad",
    start_game:       "Empezar juego",
    stations:         "Estaciónes",
    statistics:       "Estadística",
    students:         "Estudiantes",
    tax:              "Impuesto",
    taxes:            "Impuestos",
    terrain_editor:   "Editor de terreno",
    top_develop:      "Top",
    total:            "Total",
    traffic_funds:    "Fondos de Trafico",
    traffic_jam:      "Embotellamiento",
    traffic_volume:   "Volumen de tráfico",
    transportation:   "Transporte",
    unemployment:     "Desempleo",
    update:           "Actualizar",
    woods:            "Bosque",

    // Disasters
    airplane_crash:   "Choque de avion",
    earthquake:       "Terremoto",
    fire:             "Fuego",
    flood:            "Inundar",
    meltdown:         "Fusión de núcleo",
    monster:          "Monstruo",
    shipwreck:        "Naufragio",
    tornado:          "Tornado",
    ufo:              "OVNI",

    // City scale
    village:          "Colonia",
    town:             "Pueblo",
    city:             "Ciudad",
    capital:          "Capital",
    metropolis:       "Metrópoli",
    megalopolis:      "Megalópolis",

    // General
    cheap:            "Barato",
    creative:         "Creativo",
    expensive:        "Costoso",
    expert:           "Experto",
    frequent:         "Frecuente",
    high:             "Alto",
    low:              "Bajo",
    master:           "Maestro",
    medium:           "Medio",
    no:               "No",
    none:             "Ninguno",
    novice:           "Novicio",
    peaceful:         "Pacífico",
    rare:             "Raro",
    very_high:        "Superior",
    yes:              "Sí",

    // Message
    msg_airport_req:    null,
    msg_blackout:       "Ocurrió un corte de energía.",
    msg_financial_dif:  null,
    msg_gift:           "Has recibido un regalo: ",
    msg_last_1year:     "Tienes 1 año en tu mandato.",
    msg_last_2year:     "Tienes 2 años en tu mandato.",
    msg_last_3year:     "Tienes 3 años en tu mandato.",
    msg_pb_crime:       "Crimen muy alto.",
    msg_pb_pollution:   "Muy alta contaminación.",
    msg_pb_taxes:       "Impuesto demasiado alto.",
    msg_pb_traffic_jam: "Informes frecuentes de atascos de tráfico.",
    msg_pb_unemployment:null,
    msg_power_plant:    "Construir más plantas de energía.",
    msg_stadium_req:    "Los residentes exigen un estadio.",
    msg_port_req:       null,
    msg_port_st_req:    null,
    msg_see_you:        "Te veo pronto. Adiós.",
    msg_support_rate:   "¿El alcalde es bueno?",
    msg_whats_problems: "¿Cuáles son los peores problemas?",

    msg_rule_tinycity:  null,
    msg_rule_micropolis:null,

    msg_drop_files1:    "Soltar el archivo aquí",
    msg_drop_files2:    "Haga clic aquí para elegir el archivo",
    msg_city_growth:    "¡Felicidades!",
    msg_elect_lose:     "Perdiste la elección. Usted debe considerar tomar unas vacaciones.",
    msg_elect_win:      "¡Felicidades! Has sido reelegido como alcalde.",
    msg_elect_result:   "Candidato titular (Tú): {votes1} votos.\nRecién llegado: {votes2} votos.",
    msg_growth_town:    "Tu colonia ha crecido hasta convertirse en pueblo.\nKeep up the good work!",
    msg_growth_city:    "Tu pueblo ha crecido hasta convertirse en ciudad.\nReduce traffic congestion and the crime rate helps your city to grow.",
    msg_growth_capital: null,
    msg_growth_metropolis:null,
    msg_growth_megalopolis:null,

    cond_population:    null,
    cond_support_rate:  null,
    cond_probrems:      null,

    disaster_airplane_crash:null,
    disaster_earthquake:    null,
    disaster_fire:          "¡Se ha informado de un incendio!",
    disaster_flood:         null,
    disaster_meltdown:      null,
    disaster_monster:       null,
    disaster_shipwreck:     null,
    disaster_tornado:       null,
    disaster_ufo:           null,

    gift_your_house:       null,
    gift_terminal_station: null,
    gift_police_hq:        null,
    gift_fire_hq:          null,
    gift_land_fill:        null,

    decimal: ",",

    _month_name:        ["ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"],
    fn_datestr: function(year, month) {
        return this._month_name[month - 1] + " " + year;
    },
});
