'use strict';

resource.append('ja', {
    // Buildings
    airport:          "空港",
    amusement_park:   "遊園地",
    bank:             "銀行",
    bulldoze:         "整地",
    casino:           "カジノ",
    castle:           "城",
    coal_power_plant: "石炭発電所",
    crossing:         "踏切",
    c_zone:           "商業地",
    fire_dept:        "消防署",
    fire_hq:          "消防本部",
    garden:           "庭園",
    gas_power_plant:  "ガス発電所",
    goods_st:         "貨物駅",
    hospital:         "病院",
    i_zone:           "工業地",
    land:             "陸地",
    land_clear:       "平地",
    land_fill:        "埋め立て",
    monolith:         "モノリス",
    monster_statue:   "50万人記念像",
    nuke_power_plant: "原子力発電所",
    police_dept:      "警察署",
    police_hq:        "警察本部",
    railroad:         "線路",
    rail_bridge:      "鉄道橋",
    road:             "道路",
    road_bridge:      "道路橋",
    rubble:           "瓦礫",
    r_zone:           "住宅地",
    school:           "学校",
    sea_port:         "港",
    stadium:          "競技場",
    station:          "駅",
    terminal_station: "ターミナル駅",
    tower:            "タワー",
    tree:             "樹木",
    water_area:       "水域",
    wire:             "電線",
    your_house:       "市長の家",
    zoo:              "動物園",

    // UI
    all_zones:        "RCI地区",
    arrested:         "逮捕者数",
    assessed_value:   "評価額 $",
    audiences:        "観客数",
    auto_bulldoze:    "自動整地",
    bankrupt:         "破産",
    bond:             "債券支払",
    budget:           "予算",
    budget_draft:     "予算案",
    c_zones:          "商業地",
    cancel:           "キャンセル",
    city_scale:       "町の規模",
    coast:            "沿岸",
    color_bf_mode:    "色覚バリアフリー",
    commitment:       "公約",
    cost:             "費用",
    crime:            "犯罪",
    current_funds:    "現在の資金",
    debt:             "債務支払",
    developed:        "開発地",
    difficulty:       "難易度",
    disaster:         "災害",
    dispatched:       "出動回数",
    download:         "ダウンロード",
    election:         "選挙",
    election_result:  "選挙速報",
    estimeted_funds:  "来年の資金(推計)",
    evaluation:       "評価",
    expenses:         "支出",
    file:             "ファイル",
    fire_cov:         "消防分布",
    fire_depts:       "消防署",
    fire_funds:       "消防費",
    freight_volume:   "貨物量",
    funds:            "資金",
    gdp:              "総生産 $",
    generate_terrain: "地形生成",
    get_random:       "ランダムに決める",
    goto_menu:        "タイトル画面へ",
    graph:            "グラフ",
    growth_last_year: "前年比",
    help:             "ヘルプ",
    hidden_assets:    "隠し資産 $",
    hospitals:        "病院",
    housing_cost:     "住宅費",
    i_zones:          "工業地",
    island:           "島",
    import_csv:       "CSVからインポート",
    import_mp:        "Micropolisからインポート",
    incomes:          "収入",
    inspect:          "調査",
    lake:             "湖",
    land_value:       "地価",
    load_file:        "ファイルからロード",
    map:              "マップ",
    max_output:       "最大出力",
    naming_city:      "街の命名",
    next_funds:       "来年の資金",
    not_available:    "未集計",
    ok:               "OK",
    options:          "設定",
    passengers:       "乗客数",
    patients:         "患者数",
    police_cov:       "警察分布",
    police_depts:     "警察署",
    police_funds:     "警察費",
    pollution:        "公害",
    population:       "人口",
    pop_density:      "人口密度",
    pop_growth:       "人口増加率",
    popup_window:     "ポップアップウインドウ",
    power_grid:       "電力",
    power_outage:     "停電",
    power_plants:     "発電所",
    power_supplied:   "通電",
    power_req:        "電力需要",
    public_opinion:   "市民の声",
    quit:             "終了",
    r_zones:          "住宅地",
    radioactivity:    "放射能",
    river:            "河川",
    ruleset:          "ルールセット",
    save_file:        "ファイルに保存",
    scenario:         "シナリオ",
    schools:          "学校",
    score:            "得点",
    sound_effect:     "効果音",
    special_income:   "特別収入",
    start_city:       "最初から",
    start_game:       "ゲーム開始",
    stations:         "駅",
    statistics:       "統計",
    students:         "生徒数",
    tax:              "税金",
    taxes:            "税金",
    terrain_editor:   "地形エディタ",
    top_develop:      "トップ",
    total:            "合計",
    traffic_funds:    "交通維持費",
    traffic_jam:      "渋滞",
    traffic_volume:   "交通量",
    transportation:   "交通網",
    unemployment:     "失業",
    update:           "更新",
    woods:            "森林",

    // Disasters
    airplane_crash:   "飛行機墜落",
    earthquake:       "地震",
    fire:             "火災",
    flood:            "洪水",
    meltdown:         "メルトダウン",
    monster:          "モンスター",
    shipwreck:        "船難破",
    tornado:          "竜巻",
    ufo:              "UFO",

    // City scale
    village:          "村",
    town:             "町",
    city:             "都市",
    capital:          "首都",
    metropolis:       "メトロポリス",
    megalopolis:      "メガロポリス",

    // General
    cheap:            "安い",
    creative:         "クリエイティブ",
    expensive:        "高い",
    expert:           "中級",
    frequent:         "多い",
    high:             "高い",
    low:              "低い",
    master:           "上級",
    medium:           "中間",
    no:               "いいえ",
    none:             "なし",
    novice:           "初級",
    peaceful:         "ピースフル",
    rare:             "少ない",
    very_high:        "最高",
    yes:              "はい",

    // Message
    msg_airport_req:    "商業発展のために空港が必要です。",
    msg_blackout:       "停電が発生しています。",
    msg_financial_dif:  "財政が悪化しています。",
    msg_gift:           "プレゼントを受け取りました: ",
    msg_last_1year:     "市長の任期はあと1年です。",
    msg_last_2year:     "市長の任期はあと2年です。",
    msg_last_3year:     "市長の任期はあと3年です。",
    msg_pb_crime:       "犯罪が多発しています。",
    msg_pb_pollution:   "公害による汚染が進んでいます。",
    msg_pb_taxes:       "税金が高すぎます。",
    msg_pb_traffic_jam: "渋滞が多発しています。",
    msg_pb_unemployment:"失業率が悪化しています。",
    msg_power_plant:    "発電所を建設してください。",
    msg_stadium_req:    "住民が競技場を要求しています。",
    msg_port_req:       "工業発展のために港が必要です。",
    msg_port_st_req:    "工業発展のために港か貨物駅が必要です。",
    msg_see_you:        "おつかれさまでした。",
    msg_support_rate:   "市長はよくやっていると思いますか?",
    msg_whats_problems: "この町の問題点は?",

    msg_rule_tinycity:  "TinyCityルールセットは、初代SimCity®と異なります。\n列車に直接乗ることはできません。\n(駅を建てましょう)\n災害発生中は、建物を建てたり壊したりできません。\n原発は建てられません。\nガス発電所が選べますが…。",
    msg_rule_micropolis:"Micropolisルールセットは、SFC版SimCity®とほぼ同じです。\nゲームエンジンはSimCityと異なるので、同じ結果になりません。\nマップは少し大きいです。\n(128x128)",

    msg_drop_files1:    "ファイルをここにドロップ",
    msg_drop_files2:    "クリックしてファイルを選択",
    msg_city_growth:    "おめでとうございます!",
    msg_elect_lose:     "残念ですが市長選挙に落選しました。",
    msg_elect_win:      "おめでとうございます! 市長に再選しました。",
    msg_elect_result:   "現職候補 (あなた): {votes1}票\n新人候補: {votes2}票",
    msg_growth_town:    "あなたの村は「町」へと発展しました。\nこの調子でがんばりましょう。",
    msg_growth_city:    "あなたの町は「都市」へと発展しました。\n渋滞や犯罪問題の解決が重要になるでしょう。",
    msg_growth_capital: "あなたの都市は「首都」になりました。\n空港や港の建設の準備はできていますか?",
    msg_growth_metropolis:"あなたの都市は「メトロポリス」へと発展しました。\nここからがあなたの腕の見せ所です。",
    msg_growth_megalopolis:"あなたの都市は、最高レベルの「メガロポリス」へと発展しました。\n街の再開発で70万人を目指してみてはいかがでしょうか?",

    cond_population:    "人口 {pops}人以上",
    cond_support_rate:  "支持率 {rate}%以上",
    cond_probrems:      "街の問題「{probrem}」が{rate}%以下",

    disaster_airplane_crash:"飛行機事故が発生しました!",
    disaster_earthquake:    "大地震が発生しました!\n火災や停電が発生していないか、確認してください。",
    disaster_fire:          "火災が発生しました!",
    disaster_flood:         "洪水が発生しました!",
    disaster_meltdown:      "メルトダウンが発生しました!\n放射能に汚染された地域には立ち入ることができません。",
    disaster_monster:       "巨大な生物が出現しました。\nこの生物が立ち去るのを待つしかありません。",
    disaster_shipwreck:     "船が難破しました!",
    disaster_tornado:       "竜巻が発生しました!",
    disaster_ufo:           "謎の飛行物体による攻撃を受けました!",

    gift_your_house:       "この街の一番好きな場所にあなたの家を建ててみてはいかがでしょうか?",
    gift_terminal_station: "駅を建設して、周囲を活性化させましょう。利益は特別収入として加算されます。",
    gift_police_hq:        "凶悪化する犯罪に対処するため、警察本部を設置しましょう。\n通常の警察署より広い範囲をカバーできます。",
    gift_fire_hq:          "多発する火災に対処するため、消防本部を設置しましょう。\n通常の消防署より広い範囲をカバーできます。",
    gift_park_casino:      "住民のために娯楽施設を建設しましょう。\nカジノは収入が増えますが、犯罪が心配です。\n遊園地とカジノのどちらにしましょう?",
    gift_bank:             "この街に銀行を建設しましょう。\n資金が必要になった場合、$10000の融資を受けることができます。",
    gift_monster_statue:   "50万人達成おめでとうございます。\nこの像は、とある芸術家が街の発展を祝して制作したものです。",
    gift_monolith:         "おめでとうございます!! 70万人達成しました!\nこれほどの市長は他にはいないでしょう。\nえ、モノリス? 知りませんね。",
    gift_land_fill:        "開発できる土地が少なくなってきました。水域を埋め立てて土地を広げましょう。",

    fn_datestr: function(year, month) {
        return year + "年" + month + "月";
    },
    fn_yearstr: function(year) {
        return year + "年";
    },
    fn_rankstr: function(rank) {
        return rank + "位";
    },
});
