'use strict';

resource.append('zh', {
    // Buildings
    airport:          "机场",
    amusement_park:   "游乐园",
    bank:             "银行",
    bulldoze:         "推土",
    casino:           "赌场",
    castle:           "城堡",
    coal_power_plant: "煤炭发电厂",
    crossing:         "平交道",
    c_zone:           "商业区",
    fire_dept:        "消防局",
    fire_hq:          "消防总部",
    fountain:         "喷泉",
    garden:           "庭园",
    gas_power_plant:  "燃气发电厂",
    goods_st:         "货运车站",
    hospital:         "医院",
    i_zone:           "工业区",
    land:             "陆地",
    land_clear:       "平地",
    land_fill:        "填海",
    library:          "图书馆",
    monolith:         "黑石板",
    monster_statue:   "50万人纪念雕像",
    nuke_power_plant: "核能发电厂",
    police_dept:      "警察局",
    police_hq:        "警察总部",
    railroad:         "铁路",
    rail_bridge:      "铁路桥",
    road:             "道路",
    road_bridge:      "道路桥",
    rubble:           "瓦砾",
    r_zone:           "住宅区",
    school:           "学校",
    sea_port:         "港口",
    stadium:          "体育场",
    station:          "车站",
    terminal_station: "总站",
    tower:            "塔",
    tree:             "树木",
    water_area:       "水域",
    windmill:         "风车",
    wire:             "电缆",
    your_house:       "你的住宅",
    zoo:              "动物园",

    // UI
    all_zones:        "RCI街区",
    arrested:         "被捕人数",
    assessed_value:   "评估价值 $",
    audiences:        "观众数",
    auto_bulldoze:    "自動推土",
    bankrupt:         "破产",
    bond:             "债券",
    bond_5year:       "发行$2000债券 (5年)",
    bond_10year:      "发行$3000债券 (10年)",
    budget:           "预算",
    budget_draft:     "预算草案",
    c_zones:          "商业区",
    cancel:           "取消",
    city_scale:       "街区的规模",
    coast:            "滨",
    color_bf_mode:    "色彩无障碍",
    commitment:       "公开诺言",
    cost:             "用费",
    crime:            "犯罪",
    current_funds:    "目前的资金",
    debt:             "债务",
    developed:        "已开发",
    difficulty:       "难度",
    disaster:         "灾害",
    dispatched:       "出动次数",
    download:         "下载",
    election:         "选举",
    election_result:  "选举结果",
    estimeted_funds:  "明年的资金(预计)",
    evaluation:       "评估",
    expenses:         "支出",
    file:             "文件",
    fire_cov:         "消防范围",
    fire_depts:       "消防局",
    fire_funds:       "消防费用",
    freight_volume:   "货运量",
    funds:            "资金",
    gdp:              "生产总值 $",
    generate_terrain: "生成地形",
    get_random:       "随机命名",
    goto_menu:        "重新开始",
    graph:            "统计图",
    growth_last_year: "从去年比较",
    help:             "幇助",
    hidden_assets:    "隐藏的资产 $",
    hospitals:        "医院",
    housing_cost:     "住宅价格",
    i_zones:          "工业区",
    island:           "岛",
    import_csv:       "从CSV导入",
    import_mp:        "从Micropolis导入",
    incomes:          "收入",
    inspect:          "检查",
    interest:         "利息",
    lake:             "湖",
    land_value:       "土地价值",
    llama:            "大羊驼",
    load_file:        "打开文件",
    loan:             "贷款",
    map:              "地图",
    max_output:       "最大输出",
    naming_city:      "命名你的城市",
    next_funds:       "明年的资金",
    not_available:    "没有信息",
    ok:               "OK",
    options:          "选项",
    passengers:       "乗客数",
    patients:         "患者数",
    payment_complete: "付款完成年",
    payment_balance:  "付款余额",
    police_cov:       "警察范围",
    police_depts:     "警察局",
    police_funds:     "警察费用",
    pollution:        "污染",
    population:       "人口",
    pop_density:      "人口密度",
    pop_growth:       "人口増加率",
    popup_window:     "弹出窗口",
    power_grid:       "电力",
    power_outage:     "停电",
    power_plants:     "发电厂",
    power_req:        "电力需要量",
    power_supplied:   "通电",
    public_opinion:   "公众意见",
    quit:             "终了",
    r_zones:          "住宅区",
    radioactivity:    "放射能",
    river:            "河流",
    ruleset:          "规则集",
    save_file:        "保存文件",
    scenario:         "脚本",
    schools:          "学校",
    score:            "评分",
    sound_effect:     "音效",
    special_income:   "特别收入",
    start_city:       "开始新的城市",
    start_game:       "开始游戏",
    stations:         "车站",
    statistics:       "统计",
    students:         "学生数",
    tax:              "租税",
    taxes:            "租税",
    terrain_editor:   "地形编辑器",
    top_develop:      "顶级",
    total:            "总计",
    traffic_funds:    "运输费用",
    traffic_jam:      "交通堵塞",
    traffic_volume:   "汽车流量",
    transportation:   "运输网络",
    unemployment:     "失业",
    update:           "更新",
    woods:            "森林",

    // Disasters
    airplane_crash:   "飞机坠毁",
    earthquake:       "地震",
    fire:             "火灾",
    flood:            "洪水",
    meltdown:         "堆芯熔毁",
    monster:          "妖怪",
    shipwreck:        "沉船",
    tornado:          "龙捲风",
    ufo:              "飞碟",

    // City scale
    village:          "村庄",
    town:             "小镇",
    city:             "城市",
    capital:          "首都",
    metropolis:       "大都市",
    megalopolis:      "大都市带",

    // General
    cheap:            "廉价",
    creative:         "创造",
    expensive:        "高价",
    expert:           "中级",
    frequent:         "频繁",
    high:             "高",
    low:              "低",
    master:           "上级",
    medium:           "中间",
    no:               "不是",
    none:             "无",
    novice:           "初级",
    peaceful:         "和平",
    rare:             "罕见",
    very_high:        "很高",
    yes:              "是",

    // Message
    msg_airport_req:    "需要机场为商业。",
    msg_blackout:       "停电发生了。",
    msg_financial_dif:  "财务状況越来越差。",
    msg_gift:           "你收到了礼物: ",
    msg_last_1year:     "你的任期还有1年。",
    msg_last_2year:     "你的任期还有2年。",
    msg_last_3year:     "你的任期还有3年。",
    msg_pb_crime:       "犯罪率很高了。",
    msg_pb_pollution:   "污染呈加重趋势。",
    msg_pb_taxes:       "税太高了。",
    msg_pb_traffic_jam: "经常发生交通堵塞。",
    msg_pb_unemployment:"失业率很高了。",
    msg_power_plant:    "请建设更多的发电厂。",
    msg_stadium_req:    "居民要求体育场。",
    msg_port_req:       "需要港口为工业。",
    msg_port_st_req:    "需要港口或货运车站为工业。",
    msg_see_you:        "你辛苦了。再见。",
    msg_support_rate:   "市长做得好吗?",
    msg_whats_problems: "什么是最糟糕的问题?",

    msg_loan:           "每年支付$500，为期21年。",
    msg_rule_tinycity:  "TinyCity规则集与SimCity®(1989年)不同。\n居民不直接坐火车。\n(请建设车站!)\nWhile disaster occurs, you cannot build nor bulldoze any buildings.\nNuclear is no longer available.\nYou can choose gas power but ...",
    msg_rule_micropolis:"Micropolis规则集与SNES版本SimCity®几乎相同。\nGame engine is not same as SimCity's engine so you get different result.\nMap size is larger a little.\n(128x128)",

    msg_drop_files1:      "在此处拖放文件",
    msg_drop_files2:      "单击以选择文件",
    msg_city_growth:      "祝贺您!",
    msg_elect_lose:       "你输了市长选举。你应该考虑休假。",
    msg_elect_win:        "祝贺您! 你再次当选为市长。",
    msg_elect_result:     "现任候选人 (您): {votes1}票\n新人候选人: {votes2}票",
    msg_growth_town:      "你的村庄已经发展成为「小镇」。\n保持良好的工作!",
    msg_growth_city:      "你的小镇已经发展成为「城市」。\nReduce traffic congestion and the crime rate helps your city to grow.",
    msg_growth_capital:   "你的城市已成为「首都」。\n你准备建机场或港口了吗?",
    msg_growth_metropolis:"你的城市已成为「大都市」。\n是时候展示你的力量了。",
    msg_growth_megalopolis:"你的城市已达到最高類別「大都市带」。\nCan you rezone areas and increace population to 700,000? Good luck!",
    msg_bankrupt:       null,

    cond_population:    "人口不少于{pops}",
    cond_support_rate:  "支持率不低于{rate}%",
    cond_probrems:      "城市的问题「{probrem}」不高于{rate}%",

    disaster_airplane_crash:"飞机坠毁报导了!",
    disaster_earthquake:    null,
    disaster_fire:          "火灾报导了!",
    disaster_flood:         "洪水报导了!",
    disaster_meltdown:      null,
    disaster_monster:       null,
    disaster_shipwreck:     "船已经失事!",
    disaster_tornado:       "龙捲风报导了!",
    disaster_ufo:           "飞碟攻击你的城市!",

    gift_your_house:       null,
    gift_terminal_station: null,
    gift_police_hq:        null,
    gift_fire_hq:          null,
    gift_park_casino:      null,
    gift_bank_m:           null,
    gift_bank_t:           null,
    gift_zoo:              null,
    gift_windmill:         null,
    gift_library:          null,
    gift_monster_statue:   null,
    gift_monolith:         null,
    gift_land_fill:        null,

    fn_datestr: function(year, month) {
        return year + "年" + month + "月";
    },
    fn_yearstr: function(year) {
        return year + "年";
    },
    fn_rankstr: function(rank) {
        return rank + "位";
    },
});
