'use strict';

resource.append('zh_hant', {
    // Buildings
    airport:          "機場",
    amusement_park:   "遊樂園",
    bank:             "銀行",
    bulldoze:         "推土",
    casino:           "賭場",
    castle:           "城堡",
    coal_power_plant: "煤炭發電廠",
    crossing:         "平交道",
    c_zone:           "商業區",
    fire_dept:        "消防局",
    fire_hq:          "消防總部",
    garden:           "庭園",
    gas_power_plant:  "燃氣發電廠",
    goods_st:         "貨運車站",
    hospital:         "醫院",
    i_zone:           "工業區",
    land:             "陸地",
    land_clear:       "平地",
    land_fill:        "填海",
    monolith:         "黑石板",
    monster_statue:   "50万人紀念雕像",
    nuke_power_plant: "核能發電廠",
    police_dept:      "警察局",
    police_hq:        "警察總部",
    railroad:         "鐵路",
    rail_bridge:      "鐵路橋",
    road:             "道路",
    road_bridge:      "道路橋",
    rubble:           "瓦礫",
    r_zone:           "住宅區",
    school:           "學校",
    sea_port:         "港口",
    stadium:          "體育場",
    station:          "車站",
    terminal_station: "總站",
    tower:            "塔",
    tree:             "樹木",
    water_area:       "水域",
    wire:             "電纜",
    your_house:       "你的住宅",
    zoo:              "動物園",

    // UI
    all_zones:        "RCI街區",
    arrested:         "被捕人數",
    assessed_value:   "評估價值 $",
    audiences:        "觀眾數",
    auto_bulldoze:    "自動推土",
    bankrupt:         "破產",
    bond:             "債券付款",
    budget:           "預算",
    budget_draft:     "預算草案",
    c_zones:          "商業區",
    cancel:           "取消",
    city_scale:       "街區的規模",
    coast:            "濱",
    color_bf_mode:    "色彩無障礙",
    commitment:       "公開諾言",
    cost:             "用費",
    crime:            "犯罪",
    current_funds:    "目前的資金",
    debt:             "債務付款",
    developed:        "已開發",
    difficulty:       "難度",
    disaster:         "災害",
    dispatched:       "出動次數",
    download:         "下載",
    election:         "選擧",
    election_result:  "選擧結果",
    estimeted_funds:  "明年的資金(預計)",
    evaluation:       "評估",
    expenses:         "支出",
    file:             "文件",
    fire_cov:         "消防範圍",
    fire_depts:       "消防局",
    fire_funds:       "消防費用",
    freight_volume:   "貨運量",
    funds:            "資金",
    gdp:              "生產總值 $",
    generate_terrain: "生成地形",
    get_random:       "隨機命名",
    goto_menu:        "重新開始",
    graph:            "統計圖",
    growth_last_year: "從去年比較",
    help:             "幇助",
    hidden_assets:    "隱藏的資產 $",
    hospitals:        "醫院",
    housing_cost:     "住宅價格",
    i_zones:          "工業區",
    island:           "島",
    import_csv:       "從CSV導入",
    import_mp:        "從Micropolis導入",
    incomes:          "收入",
    inspect:          "檢查",
    lake:             "湖",
    land_value:       "土地價值",
    load_file:        "打開文件",
    map:              "地圖",
    max_output:       "最大輸出",
    naming_city:      "命名你的城市",
    next_funds:       "明年的資金",
    not_available:    "沒有信息",
    ok:               "OK",
    options:          "選項",
    passengers:       "乘客數",
    patients:         "患者數",
    police_cov:       "警察範圍",
    police_depts:     "警察局",
    police_funds:     "警察費用",
    pollution:        "污染",
    population:       "人口",
    pop_density:      "人口密度",
    pop_growth:       "人口増加率",
    popup_window:     "彈出窗口",
    power_grid:       "電力",
    power_outage:     "停電",
    power_plants:     "發電廠",
    power_supplied:   "通電",
    power_req:        "電力需要量",
    public_opinion:   "公眾意見",
    quit:             "終了",
    r_zones:          "住宅區",
    radioactivity:    "放射能",
    river:            "河流",
    ruleset:          "規則集",
    save_file:        "保存文件",
    scenario:         "腳本",
    schools:          "學校",
    score:            "評分",
    sound_effect:     "音效",
    special_income:   "特别收入",
    start_city:       "開始新的城市",
    start_game:       "開始遊戲",
    stations:         "車站",
    statistics:       "統計",
    students:         "學生數",
    tax:              "租稅",
    taxes:            "租稅",
    terrain_editor:   "地形編輯器",
    top_develop:      "頂級",
    total:            "總計",
    traffic_funds:    "運輸費用",
    traffic_jam:      "交通堵塞",
    traffic_volume:   "汽車流量",
    transportation:   "運輸網絡",
    unemployment:     "失業",
    update:           "更新",
    woods:            "森林",

    // Disasters
    airplane_crash:   "飛機墜毀",
    earthquake:       "地震",
    fire:             "火災",
    flood:            "洪水",
    meltdown:         "堆芯熔毁",
    monster:          "妖怪",
    shipwreck:        "沉船",
    tornado:          "龍捲風",
    ufo:              "飛碟",

    // City scale
    village:          "村莊",
    town:             "小鎮",
    city:             "城市",
    capital:          "首都",
    metropolis:       "大都市",
    megalopolis:      "大都市帶",

    // General
    cheap:            "廉價",
    creative:         "創造",
    expensive:        "高價",
    expert:           "中級",
    frequent:         "頻繁",
    high:             "高",
    low:              "低",
    master:           "上級",
    medium:           "中間",
    no:               "不是",
    none:             "無",
    novice:           "初級",
    peaceful:         "和平",
    rare:             "罕見",
    very_high:        "很高",
    yes:              "是",

    // Message
    msg_airport_req:    "需要機場爲商業。",
    msg_blackout:       "停電發生了。",
    msg_financial_dif:  "財務狀況越來越差。",
    msg_gift:           "你收到了禮物: ",
    msg_last_1year:     "你的任期還有1年。",
    msg_last_2year:     "你的任期還有2年。",
    msg_last_3year:     "你的任期還有3年。",
    msg_pb_crime:       "犯罪率很高了。",
    msg_pb_pollution:   "污染呈加重趨勢。",
    msg_pb_taxes:       "稅太高了。",
    msg_pb_traffic_jam: "經常發生交通堵塞。",
    msg_pb_unemployment:"失業率很高了。",
    msg_power_plant:    "請建設更多的發電廠。",
    msg_stadium_req:    "居民要求體育場。",
    msg_port_req:       "需要港口爲工業。",
    msg_port_st_req:    "需要港口或貨運車站爲工業。",
    msg_see_you:        "你辛苦了。再見。",
    msg_support_rate:   "市長做得好嗎?",
    msg_whats_problems: "什麼是最糟糕的問題?",

    msg_rule_tinycity:  "TinyCity規則集與SimCity®(1989年)不同。\n居民不直接坐火車。\n(請建設車站!)\nWhile disaster occurs, you cannot build nor bulldoze any buildings.\nNuclear is no longer available.\nYou can choose gas power but ...",
    msg_rule_micropolis:"Micropolis規則集與SNES版本SimCity®幾乎相同。\nGame engine is not same as SimCity's engine so you get different result.\nMap size is larger a little.\n(128x128)",

    msg_drop_files1:      "在此處拖放文件",
    msg_drop_files2:      "單擊以選擇文件",
    msg_city_growth:      "祝賀您!",
    msg_elect_lose:       "你輸了市長選舉。你應該考慮休假。",
    msg_elect_win:        "祝賀您! 你再次當選為市長。",
    msg_elect_result:     "現任候選人 (您): {votes1}票\n新人候選人: {votes2}票",
    msg_growth_town:      "你的村莊已經發展成爲「小鎮」。\n保持良好的工作!",
    msg_growth_city:      "你的小鎮已經發展成爲「城市」。\nReduce traffic congestion and the crime rate helps your city to grow.",
    msg_growth_capital:   "你的城市已成爲「首都」。\n你準備建機場或港口了嗎?",
    msg_growth_metropolis:"你的城市已成爲「大都市」。\n是時候展示你的力量了。",
    msg_growth_megalopolis:"你的城市已達到最高類別「大都市帶」。\nCan you rezone areas and increace population to 700,000? Good luck!",

    cond_population:    "人口不少於{pops}",
    cond_support_rate:  "支持率不低於{rate}%",
    cond_probrems:      "城市的問題「{probrem}」不高於{rate}%",

    disaster_airplane_crash:"飛機墜毀報導了!",
    disaster_earthquake:    null,
    disaster_fire:          "火災報導了!",
    disaster_flood:         "洪水報導了!",
    disaster_meltdown:      null,
    disaster_monster:       null,
    disaster_shipwreck:     "船已經失事!",
    disaster_tornado:       "龍捲風報導了!",
    disaster_ufo:           "飛碟攻擊你的城市!",

    gift_your_house:       null,
    gift_terminal_station: null,
    gift_police_hq:        null,
    gift_fire_hq:          null,
    gift_park_casino:      null,
    gift_bank:             null,
    gift_monster_statue:   null,
    gift_monolith:         null,
    gift_land_fill:        null,

    fn_datestr: function(year, month) {
        return year + "年" + month + "月";
    },
    fn_yearstr: function(year) {
        return year + "年";
    },
    fn_rankstr: function(rank) {
        return rank + "位";
    },
});
